# Generated by Django 3.0.5 on 2020-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchinfoapp', '0004_delete_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perk0',
            field=models.IntegerField(blank=True, db_column='perk0', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perk1',
            field=models.IntegerField(blank=True, db_column='perk1', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perk2',
            field=models.IntegerField(blank=True, db_column='perk2', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perk3',
            field=models.IntegerField(blank=True, db_column='perk3', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perk4',
            field=models.IntegerField(blank=True, db_column='perk4', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perk5',
            field=models.IntegerField(blank=True, db_column='perk5', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perkprimarystyle',
            field=models.IntegerField(blank=True, db_column='perkPrimaryStyle', null=True),
        ),
        migrations.AddField(
            model_name='matchparticipantv4',
            name='perksubstyle',
            field=models.IntegerField(blank=True, db_column='perkSubStyle', null=True),
        ),
    ]
